{
  "uid" : "cb755744659a7af5",
  "name" : "test_xfail_expected_failure",
  "fullName" : "vkr_project_tests.test_attach#test_xfail_expected_failure",
  "historyId" : "a55201de92fab6edbf92cb844607333f",
  "time" : {
    "start" : 1649447679356,
    "stop" : 1649447679356,
    "duration" : 0
  },
  "description" : "this test is an xfail that will be marked as expected failure",
  "descriptionHtml" : "<p>this test is an xfail that will be marked as expected failure</p>\n",
  "status" : "skipped",
  "statusMessage" : "XFAIL this test is expecting failure\n\nAssertionError: assert False",
  "statusTrace" : "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure():\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\nvkr_project_tests/test_attach.py:7: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(condition=<function <lambda> at 0x7f7d4766c310>, reason='this test is expecting failure')"
  }, {
    "name" : "parentSuite",
    "value" : "vkr_project_tests"
  }, {
    "name" : "suite",
    "value" : "test_attach"
  }, {
    "name" : "host",
    "value" : "fv-az135-297"
  }, {
    "name" : "thread",
    "value" : "2359-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vkr_project_tests.test_attach"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(condition=<function <lambda> at 0x7f7d4766c310>, reason='this test is expecting failure')" ]
  },
  "source" : "cb755744659a7af5.json",
  "parameterValues" : [ ]
}